module.exports = Object.freeze({
    LIGHT_BEER: 'light',
    LIGHT_BEER_DISPLAY: 'Light beer',
    LIGHT_BEER_CLASS: 'Light-beer-color',
    DARK_BEER: 'dark',
    DARK_BEER_CLASS: 'Dark-beer-color',
    DARK_BEER_DISPLAY: 'Dark beer',
    ALL_BEER: 'all',
    ALL_BEER_CLASS: 'Beer-color',
    ALL_BEER_DISPLAY: 'All beer',
    BITTERNESS: 'bitterness',
    BITTERNESS_DISPLAY: 'By bitterness',
    VOLUME: 'alc',
    VOLUME_DISPLAY: 'By volume',
    REMOVE_SORTING: 'remove_sorting',
    REMOVE_SORTING_DISPLAY: 'Remove sorting',
    ASCENDING: 'Ascending',
    DESCENDING: 'Descending',
});
