module.exports = Object.freeze({
    LIGHT_BEER: 'light',
    LIGHT_BEER_DISPLAY: 'Light beer',
    LIGHT_BEER_CLASS: 'Light-beer-color',
    DARK_BEER: 'dark',
    DARK_BEER_CLASS: 'Dark-beer-color',
    DARK_BEER_DISPLAY: 'Dark beer',
    BITTERNESS: 'bitterness',
    NAME: 'name',
    BEER_NAME_DISPLAY: 'Beer name',
    BITTERNESS_DISPLAY: 'Bitterness',
    VOLUME_DISPLAY: 'Volume',
    VOLUME: 'alc',
    NO_SORTING: 'no_sorting',
    REMOVE_SORTING_DISPLAY: 'Remove sorting',
    ASCENDING: 'Ascending',
    DESCENDING: 'Descending',
    ASCENDING_ICON: 'glyphicon glyphicon-circle-arrow-down',
    DESCENDING_ICON: 'glyphicon glyphicon-circle-arrow-up',
    API_URL: 'https://lukas-improved-pancake.herokuapp.com',
});
